[build-system]
requires = ["uv_build<0.12"]
build-backend = "uv_build"

[project]
name = "corrosions"
version = "0.3.0"
authors = [
    {name = "Martanto", email = "martanto@live.com"},
]
description = "Corrosion calculation created by Capella Global Innovation"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "joblib>=1.6.0",
    "loguru>=0.7.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.3",
    "python-slugify>=8.0.4",
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[dependency-groups]
dev = [
    "uv-build",
    "ruff",
    "ty",
    "ipykernel",
    "notebook",
    "pytest",
    "ipywidgets",
    "pandas-stubs~=3.0.3",
    "pip",
]

[tool.uv]
cache-dir = "./.cache/uv"

[project.urls]
Repository    = "https://github.com/capella-cgi/corrosions"
Documentation = "https://github.com/capella-cgi/corrosions/wiki"
Changelog     = "https://github.com/capella-cgi/corrosions/releases"
Issues        = "https://github.com/capella-cgi/corrosions/issues"
